import type { Config } from "tailwindcss";

export default {
  content: ["./app/**/*.{js,jsx,ts,tsx}"],
  theme: {
    container: {
      center: true,
      padding: "1rem",
    },
    extend: {
      fontFamily: {
        fira_code: ["Fira Code", "monospace"],
      },
      colors: {
        /** Alpha Colors */
        alpha: {
          white: {
            10: "rgb(var(--color-alpha-white) / 0.1)",
            20: "rgb(var(--color-alpha-white) / 0.2)",
            30: "rgb(var(--color-alpha-white) / 0.3)",
            40: "rgb(var(--color-alpha-white) / 0.4)",
            50: "rgb(var(--color-alpha-white) / 0.5)",
            60: "rgb(var(--color-alpha-white) / 0.6)",
            70: "rgb(var(--color-alpha-white) / 0.7)",
            80: "rgb(var(--color-alpha-white) / 0.8)",
            90: "rgb(var(--color-alpha-white) / 0.9)",
            100: "rgb(var(--color-alpha-white) / 1)",
          },
          black: {
            10: "rgb(var(--color-alpha-black) / 0.1)",
            20: "rgb(var(--color-alpha-black) / 0.2)",
            30: "rgb(var(--color-alpha-black) / 0.3)",
            40: "rgb(var(--color-alpha-black) / 0.4)",
            50: "rgb(var(--color-alpha-black) / 0.5)",
            60: "rgb(var(--color-alpha-black) / 0.6)",
            70: "rgb(var(--color-alpha-black) / 0.7)",
            80: "rgb(var(--color-alpha-black) / 0.8)",
            90: "rgb(var(--color-alpha-black) / 0.9)",
            100: "rgb(var(--color-alpha-black) / 1)",
          },
        },
        /** Primary Colors */
        brand: {
          25: "rgb(var(--color-brand-25) / <alpha-value>)",
          50: "rgb(var(--color-brand-50) / <alpha-value>)",
          100: "rgb(var(--color-brand-100) / <alpha-value>)",
          200: "rgb(var(--color-brand-200) / <alpha-value>)",
          300: "rgb(var(--color-brand-300) / <alpha-value>)",
          400: "rgb(var(--color-brand-400) / <alpha-value>)",
          500: "rgb(var(--color-brand-500) / <alpha-value>)",
          600: "rgb(var(--color-brand-600) / <alpha-value>)",
          700: "rgb(var(--color-brand-700) / <alpha-value>)",
          800: "rgb(var(--color-brand-800) / <alpha-value>)",
          900: "rgb(var(--color-brand-900) / <alpha-value>)",
          950: "rgb(var(--color-brand-950) / <alpha-value>)",
          utility: {
            50: "rgb(var(--color-brand-utility-50) / <alpha-value>)",
            100: "rgb(var(--color-brand-utility-100) / <alpha-value>)",
            200: "rgb(var(--color-brand-utility-200) / <alpha-value>)",
            300: "rgb(var(--color-brand-utility-300) / <alpha-value>)",
            400: "rgb(var(--color-brand-utility-400) / <alpha-value>)",
            500: "rgb(var(--color-brand-utility-500) / <alpha-value>)",
            600: "rgb(var(--color-brand-utility-600) / <alpha-value>)",
            700: "rgb(var(--color-brand-utility-700) / <alpha-value>)",
            800: "rgb(var(--color-brand-utility-800) / <alpha-value>)",
            900: "rgb(var(--color-brand-utility-900) / <alpha-value>)",
          },
        },
        gray: {
          25: "rgb(var(--color-gray-25) / <alpha-value>)",
          50: "rgb(var(--color-gray-50) / <alpha-value>)",
          100: "rgb(var(--color-gray-100) / <alpha-value>)",
          200: "rgb(var(--color-gray-200) / <alpha-value>)",
          300: "rgb(var(--color-gray-300) / <alpha-value>)",
          400: "rgb(var(--color-gray-400) / <alpha-value>)",
          500: "rgb(var(--color-gray-500) / <alpha-value>)",
          600: "rgb(var(--color-gray-600) / <alpha-value>)",
          700: "rgb(var(--color-gray-700) / <alpha-value>)",
          800: "rgb(var(--color-gray-800) / <alpha-value>)",
          900: "rgb(var(--color-gray-900) / <alpha-value>)",
          950: "rgb(var(--color-gray-950) / <alpha-value>)",
          utility: {
            50: "rgb(var(--color-gray-utility-50) / <alpha-value>)",
            100: "rgb(var(--color-gray-utility-100) / <alpha-value>)",
            200: "rgb(var(--color-gray-utility-200) / <alpha-value>)",
            300: "rgb(var(--color-gray-utility-300) / <alpha-value>)",
            400: "rgb(var(--color-gray-utility-400) / <alpha-value>)",
            500: "rgb(var(--color-gray-utility-500) / <alpha-value>)",
            600: "rgb(var(--color-gray-utility-600) / <alpha-value>)",
            700: "rgb(var(--color-gray-utility-700) / <alpha-value>)",
            800: "rgb(var(--color-gray-utility-800) / <alpha-value>)",
            900: "rgb(var(--color-gray-utility-900) / <alpha-value>)",
          },
        },
        error: {
          25: "rgb(var(--color-error-25) / <alpha-value>)",
          50: "rgb(var(--color-error-50) / <alpha-value>)",
          100: "rgb(var(--color-error-100) / <alpha-value>)",
          200: "rgb(var(--color-error-200) / <alpha-value>)",
          300: "rgb(var(--color-error-300) / <alpha-value>)",
          400: "rgb(var(--color-error-400) / <alpha-value>)",
          500: "rgb(var(--color-error-500) / <alpha-value>)",
          600: "rgb(var(--color-error-600) / <alpha-value>)",
          700: "rgb(var(--color-error-700) / <alpha-value>)",
          800: "rgb(var(--color-error-800) / <alpha-value>)",
          900: "rgb(var(--color-error-900) / <alpha-value>)",
          950: "rgb(var(--color-error-950) / <alpha-value>)",
          utility: {
            50: "rgb(var(--color-error-utility-50) / <alpha-value>)",
            100: "rgb(var(--color-error-utility-100) / <alpha-value>)",
            200: "rgb(var(--color-error-utility-200) / <alpha-value>)",
            300: "rgb(var(--color-error-utility-300) / <alpha-value>)",
            400: "rgb(var(--color-error-utility-400) / <alpha-value>)",
            500: "rgb(var(--color-error-utility-500) / <alpha-value>)",
            600: "rgb(var(--color-error-utility-600) / <alpha-value>)",
            700: "rgb(var(--color-error-utility-700) / <alpha-value>)",
          },
        },
        warning: {
          25: "rgb(var(--color-warning-25) / <alpha-value>)",
          50: "rgb(var(--color-warning-50) / <alpha-value>)",
          100: "rgb(var(--color-warning-100) / <alpha-value>)",
          200: "rgb(var(--color-warning-200) / <alpha-value>)",
          300: "rgb(var(--color-warning-300) / <alpha-value>)",
          400: "rgb(var(--color-warning-400) / <alpha-value>)",
          500: "rgb(var(--color-warning-500) / <alpha-value>)",
          600: "rgb(var(--color-warning-600) / <alpha-value>)",
          700: "rgb(var(--color-warning-700) / <alpha-value>)",
          800: "rgb(var(--color-warning-800) / <alpha-value>)",
          900: "rgb(var(--color-warning-900) / <alpha-value>)",
          950: "rgb(var(--color-warning-950) / <alpha-value>)",
          utility: {
            50: "rgb(var(--color-warning-utility-50) / <alpha-value>)",
            100: "rgb(var(--color-warning-utility-100) / <alpha-value>)",
            200: "rgb(var(--color-warning-utility-200) / <alpha-value>)",
            300: "rgb(var(--color-warning-utility-300) / <alpha-value>)",
            400: "rgb(var(--color-warning-utility-400) / <alpha-value>)",
            500: "rgb(var(--color-warning-utility-500) / <alpha-value>)",
            600: "rgb(var(--color-warning-utility-600) / <alpha-value>)",
            700: "rgb(var(--color-warning-utility-700) / <alpha-value>)",
          },
        },
        success: {
          25: "rgb(var(--color-success-25) / <alpha-value>)",
          50: "rgb(var(--color-success-50) / <alpha-value>)",
          100: "rgb(var(--color-success-100) / <alpha-value>)",
          200: "rgb(var(--color-success-200) / <alpha-value>)",
          300: "rgb(var(--color-success-300) / <alpha-value>)",
          400: "rgb(var(--color-success-400) / <alpha-value>)",
          500: "rgb(var(--color-success-500) / <alpha-value>)",
          600: "rgb(var(--color-success-600) / <alpha-value>)",
          700: "rgb(var(--color-success-700) / <alpha-value>)",
          800: "rgb(var(--color-success-800) / <alpha-value>)",
          900: "rgb(var(--color-success-900) / <alpha-value>)",
          950: "rgb(var(--color-success-950) / <alpha-value>)",
          utility: {
            50: "rgb(var(--color-success-utility-50) / <alpha-value>)",
            100: "rgb(var(--color-success-utility-100) / <alpha-value>)",
            200: "rgb(var(--color-success-utility-200) / <alpha-value>)",
            300: "rgb(var(--color-success-utility-300) / <alpha-value>)",
            400: "rgb(var(--color-success-utility-400) / <alpha-value>)",
            500: "rgb(var(--color-success-utility-500) / <alpha-value>)",
            600: "rgb(var(--color-success-utility-600) / <alpha-value>)",
            700: "rgb(var(--color-success-utility-700) / <alpha-value>)",
          },
        },
        /** Secondary Colors */
        moss: {
          25: "rgb(var(--color-moss-25) / <alpha-value>)",
          50: "rgb(var(--color-moss-50) / <alpha-value>)",
          100: "rgb(var(--color-moss-100) / <alpha-value>)",
          200: "rgb(var(--color-moss-200) / <alpha-value>)",
          300: "rgb(var(--color-moss-300) / <alpha-value>)",
          400: "rgb(var(--color-moss-400) / <alpha-value>)",
          500: "rgb(var(--color-moss-500) / <alpha-value>)",
          600: "rgb(var(--color-moss-600) / <alpha-value>)",
          700: "rgb(var(--color-moss-700) / <alpha-value>)",
          800: "rgb(var(--color-moss-800) / <alpha-value>)",
          900: "rgb(var(--color-moss-900) / <alpha-value>)",
          950: "rgb(var(--color-moss-950) / <alpha-value>)",
        },
        "green-light": {
          25: "rgb(var(--color-green-light-25) / <alpha-value>)",
          50: "rgb(var(--color-green-light-50) / <alpha-value>)",
          100: "rgb(var(--color-green-light-100) / <alpha-value>)",
          200: "rgb(var(--color-green-light-200) / <alpha-value>)",
          300: "rgb(var(--color-green-light-300) / <alpha-value>)",
          400: "rgb(var(--color-green-light-400) / <alpha-value>)",
          500: "rgb(var(--color-green-light-500) / <alpha-value>)",
          600: "rgb(var(--color-green-light-600) / <alpha-value>)",
          700: "rgb(var(--color-green-light-700) / <alpha-value>)",
          800: "rgb(var(--color-green-light-800) / <alpha-value>)",
          900: "rgb(var(--color-green-light-900) / <alpha-value>)",
          950: "rgb(var(--color-green-light-950) / <alpha-value>)",
        },
        green: {
          25: "rgb(var(--color-green-25) / <alpha-value>)",
          50: "rgb(var(--color-green-50) / <alpha-value>)",
          100: "rgb(var(--color-green-100) / <alpha-value>)",
          200: "rgb(var(--color-green-200) / <alpha-value>)",
          300: "rgb(var(--color-green-300) / <alpha-value>)",
          400: "rgb(var(--color-green-400) / <alpha-value>)",
          500: "rgb(var(--color-green-500) / <alpha-value>)",
          600: "rgb(var(--color-green-600) / <alpha-value>)",
          700: "rgb(var(--color-green-700) / <alpha-value>)",
          800: "rgb(var(--color-green-800) / <alpha-value>)",
          900: "rgb(var(--color-green-900) / <alpha-value>)",
          950: "rgb(var(--color-green-950) / <alpha-value>)",
        },
        teal: {
          25: "rgb(var(--color-teal-25) / <alpha-value>)",
          50: "rgb(var(--color-teal-50) / <alpha-value>)",
          100: "rgb(var(--color-teal-100) / <alpha-value>)",
          200: "rgb(var(--color-teal-200) / <alpha-value>)",
          300: "rgb(var(--color-teal-300) / <alpha-value>)",
          400: "rgb(var(--color-teal-400) / <alpha-value>)",
          500: "rgb(var(--color-teal-500) / <alpha-value>)",
          600: "rgb(var(--color-teal-600) / <alpha-value>)",
          700: "rgb(var(--color-teal-700) / <alpha-value>)",
          800: "rgb(var(--color-teal-800) / <alpha-value>)",
          900: "rgb(var(--color-teal-900) / <alpha-value>)",
          950: "rgb(var(--color-teal-950) / <alpha-value>)",
        },
        cyan: {
          25: "rgb(var(--color-cyan-25) / <alpha-value>)",
          50: "rgb(var(--color-cyan-50) / <alpha-value>)",
          100: "rgb(var(--color-cyan-100) / <alpha-value>)",
          200: "rgb(var(--color-cyan-200) / <alpha-value>)",
          300: "rgb(var(--color-cyan-300) / <alpha-value>)",
          400: "rgb(var(--color-cyan-400) / <alpha-value>)",
          500: "rgb(var(--color-cyan-500) / <alpha-value>)",
          600: "rgb(var(--color-cyan-600) / <alpha-value>)",
          700: "rgb(var(--color-cyan-700) / <alpha-value>)",
          800: "rgb(var(--color-cyan-800) / <alpha-value>)",
          900: "rgb(var(--color-cyan-900) / <alpha-value>)",
          950: "rgb(var(--color-cyan-950) / <alpha-value>)",
        },
        "blue-light": {
          25: "rgb(var(--color-blue-light-25) / <alpha-value>)",
          50: "rgb(var(--color-blue-light-50) / <alpha-value>)",
          100: "rgb(var(--color-blue-light-100) / <alpha-value>)",
          200: "rgb(var(--color-blue-light-200) / <alpha-value>)",
          300: "rgb(var(--color-blue-light-300) / <alpha-value>)",
          400: "rgb(var(--color-blue-light-400) / <alpha-value>)",
          500: "rgb(var(--color-blue-light-500) / <alpha-value>)",
          600: "rgb(var(--color-blue-light-600) / <alpha-value>)",
          700: "rgb(var(--color-blue-light-700) / <alpha-value>)",
          800: "rgb(var(--color-blue-light-800) / <alpha-value>)",
          900: "rgb(var(--color-blue-light-900) / <alpha-value>)",
          950: "rgb(var(--color-blue-light-950) / <alpha-value>)",
          utility: {
            50: "rgb(var(--color-blue-light-utility-50) / <alpha-value>)",
            100: "rgb(var(--color-blue-light-utility-100) / <alpha-value>)",
            200: "rgb(var(--color-blue-light-utility-200) / <alpha-value>)",
            300: "rgb(var(--color-blue-light-utility-300) / <alpha-value>)",
            400: "rgb(var(--color-blue-light-utility-400) / <alpha-value>)",
            500: "rgb(var(--color-blue-light-utility-500) / <alpha-value>)",
            600: "rgb(var(--color-blue-light-utility-600) / <alpha-value>)",
            700: "rgb(var(--color-blue-light-utility-700) / <alpha-value>)",
          },
        },
        blue: {
          25: "rgb(var(--color-blue-25) / <alpha-value>)",
          50: "rgb(var(--color-blue-50) / <alpha-value>)",
          100: "rgb(var(--color-blue-100) / <alpha-value>)",
          200: "rgb(var(--color-blue-200) / <alpha-value>)",
          300: "rgb(var(--color-blue-300) / <alpha-value>)",
          400: "rgb(var(--color-blue-400) / <alpha-value>)",
          500: "rgb(var(--color-blue-500) / <alpha-value>)",
          600: "rgb(var(--color-blue-600) / <alpha-value>)",
          700: "rgb(var(--color-blue-700) / <alpha-value>)",
          800: "rgb(var(--color-blue-800) / <alpha-value>)",
          900: "rgb(var(--color-blue-900) / <alpha-value>)",
          950: "rgb(var(--color-blue-950) / <alpha-value>)",
          utility: {
            50: "rgb(var(--color-blue-utility-50) / <alpha-value>)",
            100: "rgb(var(--color-blue-utility-100) / <alpha-value>)",
            200: "rgb(var(--color-blue-utility-200) / <alpha-value>)",
            300: "rgb(var(--color-blue-utility-300) / <alpha-value>)",
            400: "rgb(var(--color-blue-utility-400) / <alpha-value>)",
            500: "rgb(var(--color-blue-utility-500) / <alpha-value>)",
            600: "rgb(var(--color-blue-utility-600) / <alpha-value>)",
            700: "rgb(var(--color-blue-utility-700) / <alpha-value>)",
          },
        },
        "blue-dark": {
          25: "rgb(var(--color-blue-dark-25) / <alpha-value>)",
          50: "rgb(var(--color-blue-dark-50) / <alpha-value>)",
          100: "rgb(var(--color-blue-dark-100) / <alpha-value>)",
          200: "rgb(var(--color-blue-dark-200) / <alpha-value>)",
          300: "rgb(var(--color-blue-dark-300) / <alpha-value>)",
          400: "rgb(var(--color-blue-dark-400) / <alpha-value>)",
          500: "rgb(var(--color-blue-dark-500) / <alpha-value>)",
          600: "rgb(var(--color-blue-dark-600) / <alpha-value>)",
          700: "rgb(var(--color-blue-dark-700) / <alpha-value>)",
          800: "rgb(var(--color-blue-dark-800) / <alpha-value>)",
          900: "rgb(var(--color-blue-dark-900) / <alpha-value>)",
          950: "rgb(var(--color-blue-dark-950) / <alpha-value>)",
          utility: {
            50: "rgb(var(--color-blue-dark-utility-50) / <alpha-value>)",
            100: "rgb(var(--color-blue-dark-utility-100) / <alpha-value>)",
            200: "rgb(var(--color-blue-dark-utility-200) / <alpha-value>)",
            300: "rgb(var(--color-blue-dark-utility-300) / <alpha-value>)",
            400: "rgb(var(--color-blue-dark-utility-400) / <alpha-value>)",
            500: "rgb(var(--color-blue-dark-utility-500) / <alpha-value>)",
            600: "rgb(var(--color-blue-dark-utility-600) / <alpha-value>)",
            700: "rgb(var(--color-blue-dark-utility-700) / <alpha-value>)",
          },
        },
        indigo: {
          25: "rgb(var(--color-indigo-25) / <alpha-value>)",
          50: "rgb(var(--color-indigo-50) / <alpha-value>)",
          100: "rgb(var(--color-indigo-100) / <alpha-value>)",
          200: "rgb(var(--color-indigo-200) / <alpha-value>)",
          300: "rgb(var(--color-indigo-300) / <alpha-value>)",
          400: "rgb(var(--color-indigo-400) / <alpha-value>)",
          500: "rgb(var(--color-indigo-500) / <alpha-value>)",
          600: "rgb(var(--color-indigo-600) / <alpha-value>)",
          700: "rgb(var(--color-indigo-700) / <alpha-value>)",
          800: "rgb(var(--color-indigo-800) / <alpha-value>)",
          900: "rgb(var(--color-indigo-900) / <alpha-value>)",
          950: "rgb(var(--color-indigo-950) / <alpha-value>)",
          utility: {
            50: "rgb(var(--color-indigo-utility-50) / <alpha-value>)",
            100: "rgb(var(--color-indigo-utility-100) / <alpha-value>)",
            200: "rgb(var(--color-indigo-utility-200) / <alpha-value>)",
            300: "rgb(var(--color-indigo-utility-300) / <alpha-value>)",
            400: "rgb(var(--color-indigo-utility-400) / <alpha-value>)",
            500: "rgb(var(--color-indigo-utility-500) / <alpha-value>)",
            600: "rgb(var(--color-indigo-utility-600) / <alpha-value>)",
            700: "rgb(var(--color-indigo-utility-700) / <alpha-value>)",
          },
        },
        violet: {
          25: "rgb(var(--color-violet-25) / <alpha-value>)",
          50: "rgb(var(--color-violet-50) / <alpha-value>)",
          100: "rgb(var(--color-violet-100) / <alpha-value>)",
          200: "rgb(var(--color-violet-200) / <alpha-value>)",
          300: "rgb(var(--color-violet-300) / <alpha-value>)",
          400: "rgb(var(--color-violet-400) / <alpha-value>)",
          500: "rgb(var(--color-violet-500) / <alpha-value>)",
          600: "rgb(var(--color-violet-600) / <alpha-value>)",
          700: "rgb(var(--color-violet-700) / <alpha-value>)",
          800: "rgb(var(--color-violet-800) / <alpha-value>)",
          900: "rgb(var(--color-violet-900) / <alpha-value>)",
          950: "rgb(var(--color-violet-950) / <alpha-value>)",
        },
        purple: {
          25: "rgb(var(--color-purple-25) / <alpha-value>)",
          50: "rgb(var(--color-purple-50) / <alpha-value>)",
          100: "rgb(var(--color-purple-100) / <alpha-value>)",
          200: "rgb(var(--color-purple-200) / <alpha-value>)",
          300: "rgb(var(--color-purple-300) / <alpha-value>)",
          400: "rgb(var(--color-purple-400) / <alpha-value>)",
          500: "rgb(var(--color-purple-500) / <alpha-value>)",
          600: "rgb(var(--color-purple-600) / <alpha-value>)",
          700: "rgb(var(--color-purple-700) / <alpha-value>)",
          800: "rgb(var(--color-purple-800) / <alpha-value>)",
          900: "rgb(var(--color-purple-900) / <alpha-value>)",
          950: "rgb(var(--color-purple-950) / <alpha-value>)",
          utility: {
            50: "rgb(var(--color-purple-utility-50) / <alpha-value>)",
            100: "rgb(var(--color-purple-utility-100) / <alpha-value>)",
            200: "rgb(var(--color-purple-utility-200) / <alpha-value>)",
            300: "rgb(var(--color-purple-utility-300) / <alpha-value>)",
            400: "rgb(var(--color-purple-utility-400) / <alpha-value>)",
            500: "rgb(var(--color-purple-utility-500) / <alpha-value>)",
            600: "rgb(var(--color-purple-utility-600) / <alpha-value>)",
            700: "rgb(var(--color-purple-utility-700) / <alpha-value>)",
          },
        },
        fuschia: {
          25: "rgb(var(--color-fuschia-25) / <alpha-value>)",
          50: "rgb(var(--color-fuschia-50) / <alpha-value>)",
          100: "rgb(var(--color-fuschia-100) / <alpha-value>)",
          200: "rgb(var(--color-fuschia-200) / <alpha-value>)",
          300: "rgb(var(--color-fuschia-300) / <alpha-value>)",
          400: "rgb(var(--color-fuschia-400) / <alpha-value>)",
          500: "rgb(var(--color-fuschia-500) / <alpha-value>)",
          600: "rgb(var(--color-fuschia-600) / <alpha-value>)",
          700: "rgb(var(--color-fuschia-700) / <alpha-value>)",
          800: "rgb(var(--color-fuschia-800) / <alpha-value>)",
          900: "rgb(var(--color-fuschia-900) / <alpha-value>)",
          950: "rgb(var(--color-fuschia-950) / <alpha-value>)",
          utility: {
            50: "rgb(var(--color-fuschia-utility-50) / <alpha-value>)",
            100: "rgb(var(--color-fuschia-utility-100) / <alpha-value>)",
            200: "rgb(var(--color-fuschia-utility-200) / <alpha-value>)",
            300: "rgb(var(--color-fuschia-utility-300) / <alpha-value>)",
            400: "rgb(var(--color-fuschia-utility-400) / <alpha-value>)",
            500: "rgb(var(--color-fuschia-utility-500) / <alpha-value>)",
            600: "rgb(var(--color-fuschia-utility-600) / <alpha-value>)",
            700: "rgb(var(--color-fuschia-utility-700) / <alpha-value>)",
          },
        },
        pink: {
          25: "rgb(var(--color-pink-25) / <alpha-value>)",
          50: "rgb(var(--color-pink-50) / <alpha-value>)",
          100: "rgb(var(--color-pink-100) / <alpha-value>)",
          200: "rgb(var(--color-pink-200) / <alpha-value>)",
          300: "rgb(var(--color-pink-300) / <alpha-value>)",
          400: "rgb(var(--color-pink-400) / <alpha-value>)",
          500: "rgb(var(--color-pink-500) / <alpha-value>)",
          600: "rgb(var(--color-pink-600) / <alpha-value>)",
          700: "rgb(var(--color-pink-700) / <alpha-value>)",
          800: "rgb(var(--color-pink-800) / <alpha-value>)",
          900: "rgb(var(--color-pink-900) / <alpha-value>)",
          950: "rgb(var(--color-pink-950) / <alpha-value>)",
          utility: {
            50: "rgb(var(--color-pink-utility-50) / <alpha-value>)",
            100: "rgb(var(--color-pink-utility-100) / <alpha-value>)",
            200: "rgb(var(--color-pink-utility-200) / <alpha-value>)",
            300: "rgb(var(--color-pink-utility-300) / <alpha-value>)",
            400: "rgb(var(--color-pink-utility-400) / <alpha-value>)",
            500: "rgb(var(--color-pink-utility-500) / <alpha-value>)",
            600: "rgb(var(--color-pink-utility-600) / <alpha-value>)",
            700: "rgb(var(--color-pink-utility-700) / <alpha-value>)",
          },
        },
        rose: {
          25: "rgb(var(--color-rose-25) / <alpha-value>)",
          50: "rgb(var(--color-rose-50) / <alpha-value>)",
          100: "rgb(var(--color-rose-100) / <alpha-value>)",
          200: "rgb(var(--color-rose-200) / <alpha-value>)",
          300: "rgb(var(--color-rose-300) / <alpha-value>)",
          400: "rgb(var(--color-rose-400) / <alpha-value>)",
          500: "rgb(var(--color-rose-500) / <alpha-value>)",
          600: "rgb(var(--color-rose-600) / <alpha-value>)",
          700: "rgb(var(--color-rose-700) / <alpha-value>)",
          800: "rgb(var(--color-rose-800) / <alpha-value>)",
          900: "rgb(var(--color-rose-900) / <alpha-value>)",
          950: "rgb(var(--color-rose-950) / <alpha-value>)",
        },
        "orange-dark": {
          25: "rgb(var(--color-orange-dark-25) / <alpha-value>)",
          50: "rgb(var(--color-orange-dark-50) / <alpha-value>)",
          100: "rgb(var(--color-orange-dark-100) / <alpha-value>)",
          200: "rgb(var(--color-orange-dark-200) / <alpha-value>)",
          300: "rgb(var(--color-orange-dark-300) / <alpha-value>)",
          400: "rgb(var(--color-orange-dark-400) / <alpha-value>)",
          500: "rgb(var(--color-orange-dark-500) / <alpha-value>)",
          600: "rgb(var(--color-orange-dark-600) / <alpha-value>)",
          700: "rgb(var(--color-orange-dark-700) / <alpha-value>)",
          800: "rgb(var(--color-orange-dark-800) / <alpha-value>)",
          900: "rgb(var(--color-orange-dark-900) / <alpha-value>)",
          950: "rgb(var(--color-orange-dark-950) / <alpha-value>)",
          utility: {
            50: "rgb(var(--color-orange-dark-utility-50) / <alpha-value>)",
            100: "rgb(var(--color-orange-dark-utility-100) / <alpha-value>)",
            200: "rgb(var(--color-orange-dark-utility-200) / <alpha-value>)",
            300: "rgb(var(--color-orange-dark-utility-300) / <alpha-value>)",
            400: "rgb(var(--color-orange-dark-utility-400) / <alpha-value>)",
            500: "rgb(var(--color-orange-dark-utility-500) / <alpha-value>)",
            600: "rgb(var(--color-orange-dark-utility-600) / <alpha-value>)",
            700: "rgb(var(--color-orange-dark-utility-700) / <alpha-value>)",
          },
        },
        orange: {
          25: "rgb(var(--color-orange-25) / <alpha-value>)",
          50: "rgb(var(--color-orange-50) / <alpha-value>)",
          100: "rgb(var(--color-orange-100) / <alpha-value>)",
          200: "rgb(var(--color-orange-200) / <alpha-value>)",
          300: "rgb(var(--color-orange-300) / <alpha-value>)",
          400: "rgb(var(--color-orange-400) / <alpha-value>)",
          500: "rgb(var(--color-orange-500) / <alpha-value>)",
          600: "rgb(var(--color-orange-600) / <alpha-value>)",
          700: "rgb(var(--color-orange-700) / <alpha-value>)",
          800: "rgb(var(--color-orange-800) / <alpha-value>)",
          900: "rgb(var(--color-orange-900) / <alpha-value>)",
          950: "rgb(var(--color-orange-950) / <alpha-value>)",
          utility: {
            50: "rgb(var(--color-orange-utility-50) / <alpha-value>)",
            100: "rgb(var(--color-orange-utility-100) / <alpha-value>)",
            200: "rgb(var(--color-orange-utility-200) / <alpha-value>)",
            300: "rgb(var(--color-orange-utility-300) / <alpha-value>)",
            400: "rgb(var(--color-orange-utility-400) / <alpha-value>)",
            500: "rgb(var(--color-orange-utility-500) / <alpha-value>)",
            600: "rgb(var(--color-orange-utility-600) / <alpha-value>)",
            700: "rgb(var(--color-orange-utility-700) / <alpha-value>)",
          },
        },
        yellow: {
          25: "rgb(var(--color-yellow-25) / <alpha-value>)",
          50: "rgb(var(--color-yellow-50) / <alpha-value>)",
          100: "rgb(var(--color-yellow-100) / <alpha-value>)",
          200: "rgb(var(--color-yellow-200) / <alpha-value>)",
          300: "rgb(var(--color-yellow-300) / <alpha-value>)",
          400: "rgb(var(--color-yellow-400) / <alpha-value>)",
          500: "rgb(var(--color-yellow-500) / <alpha-value>)",
          600: "rgb(var(--color-yellow-600) / <alpha-value>)",
          700: "rgb(var(--color-yellow-700) / <alpha-value>)",
          800: "rgb(var(--color-yellow-800) / <alpha-value>)",
          900: "rgb(var(--color-yellow-900) / <alpha-value>)",
          950: "rgb(var(--color-yellow-950) / <alpha-value>)",
        },
        /** Foreground Colors */
        fg: {
          primary: "rgb(var(--color-fg-primary) / <alpha-value>)",
          secondary: "rgb(var(--color-fg-secondary) / <alpha-value>)",
          secondary_hover:
            "rgb(var(--color-fg-secondary_hover) / <alpha-value>)",
          tertiary: "rgb(var(--color-fg-tertiary) / <alpha-value>)",
          tertiary_hover: "rgb(var(--color-fg-tertiary_hover) / <alpha-value>)",
          quaternary: "rgb(var(--color-fg-quaternary) / <alpha-value>)",
          quaternary_hover:
            "rgb(var(--color-fg-quaternary_hover) / <alpha-value>)",
          quinary: "rgb(var(--color-fg-quinary) / <alpha-value>)",
          quinary_hover: "rgb(var(--color-fg-quinary_hover) / <alpha-value>)",
          senary: "rgb(var(--color-fg-senary) / <alpha-value>)",
          disabled: "rgb(var(--color-fg-disabled) / <alpha-value>)",
          disabled_subtle:
            "rgb(var(--color-fg-disabled_subtle) / <alpha-value>)",
          "brand-primary": "rgb(var(--color-fg-brand-primary) / <alpha-value>)",
          "brand-secondary":
            "rgb(var(--color-fg-brand-secondary) / <alpha-value>)",
          "error-primary": "rgb(var(--color-fg-error-primary) / <alpha-value>)",
          "error-secondary":
            "rgb(var(--color-fg-error-secondary) / <alpha-value>)",
          "warning-primary":
            "rgb(var(--color-fg-warning-primary) / <alpha-value>)",
          "warning-secondary":
            "rgb(var(--color-fg-warning-secondary) / <alpha-value>)",
          "success-primary":
            "rgb(var(--color-fg-success-primary) / <alpha-value>)",
          "success-secondary":
            "rgb(var(--color-fg-success-secondary) / <alpha-value>)",
        },
      },
      backgroundColor: {
        primary: "rgb(var(--color-bg-primary) / <alpha-value>)",
        primary_hover: "rgb(var(--color-bg-primary_hover) / <alpha-value>)",
        primary_solid: "rgb(var(--color-bg-primary-solid) / <alpha-value>)",
        secondary: "rgb(var(--color-bg-secondary) / <alpha-value>)",
        secondary_hover: "rgb(var(--color-bg-secondary_hover) / <alpha-value>)",
        secondary_subtle:
          "rgb(var(--color-bg-secondary_subtle) / <alpha-value>)",
        secondary_solid: "rgb(var(--color-bg-secondary-solid) / <alpha-value>)",
        tertiary: "rgb(var(--color-bg-tertiary) / <alpha-value>)",
        quaternary: "rgb(var(--color-bg-quaternary) / <alpha-value>)",
        active: "rgb(var(--color-bg-active) / <alpha-value>)",
        disabled: "rgb(var(--color-bg-disabled) / <alpha-value>)",
        disabled_subtle: "rgb(var(--color-bg-disabled_subtle) / <alpha-value>)",
        overlay: "rgb(var(--color-bg-overlay) / <alpha-value>)",
      },
      textColor: {
        primary: "rgb(var(--color-text-primary) / <alpha-value>)",
        primary_brand: "rgb(var(--color-text-primary_brand) / <alpha-value>)",
        secondary: "rgb(var(--color-text-secondary) / <alpha-value>)",
        secondary_hover:
          "rgb(var(--color-text-secondary_hover) / <alpha-value>)",
        secondary_brand:
          "rgb(var(--color-text-secondary_brand) / <alpha-value>)",
        tertiary: "rgb(var(--color-text-tertiary) / <alpha-value>)",
        tertiary_hover: "rgb(var(--color-text-tertiary_hover) / <alpha-value>)",
        tertiary_brand: "rgb(var(--color-text-tertiary_brand) / <alpha-value>)",
        quaternary: "rgb(var(--color-text-quaternary) / <alpha-value>)",
        quaternary_brand:
          "rgb(var(--color-text-quaternary_brand) / <alpha-value>)",
        disabled: "rgb(var(--color-text-disabled) / <alpha-value>)",
        placeholder: "rgb(var(--color-text-placeholder) / <alpha-value>)",
        placeholder_subtle:
          "rgb(var(--color-text-placeholder_subtle) / <alpha-value>)",
      },

      borderColor: {
        primary: "rgb(var(--color-border-primary) / <alpha-value>)",
        secondary: "rgb(var(--color-border-secondary) / <alpha-value>)",
        tertiary: "rgb(var(--color-border-tertiary) / <alpha-value>)",
        disabled: "rgb(var(--color-border-disabled) / <alpha-value>)",
        disabled_subtle:
          "rgb(var(--color-border-disabled_subtle) / <alpha-value>)",
      },
      boxShadow: {
        xs: "var(--box-shadow-xs)",
        sm: "var(--box-shadow-sm)",
        md: "var(--box-shadow-md)",
        lg: "var(--box-shadow-lg)",
        xl: "var(--box-shadow-xl)",
      },
      fontSize: {
        xs: ["0.75rem", { lineHeight: "1.125rem" }],
        sm: ["0.875rem", { lineHeight: "1.25rem" }],
        base: ["1rem", { lineHeight: "1.5rem" }],
        lg: ["1.125rem", { lineHeight: "1.75rem" }],
        xl: ["1.25rem", { lineHeight: "1.875rem" }],
      },
      animation: {
        "meteor-effect": "meteor 5s linear infinite",
      },
      keyframes: {
        meteor: {
          "0%": { transform: "rotate(215deg) translateX(0)", opacity: "1" },
          "70%": { opacity: "1" },
          "100%": {
            transform: "rotate(215deg) translateX(-500px)",
            opacity: "0",
          },
        },
      },
    },
  },
  plugins: [],
} satisfies Config;
